// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package http

import (
	"com.ardafirdausr.cupid/app/http/handler"
	"com.ardafirdausr.cupid/internal"
	"com.ardafirdausr.cupid/internal/pkg/jwt"
	"com.ardafirdausr.cupid/internal/pkg/mongo"
	"com.ardafirdausr.cupid/internal/pkg/validator"
	mongo2 "com.ardafirdausr.cupid/internal/repository/mongo"
	"com.ardafirdausr.cupid/internal/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func InitializeApp() (*app, func(), error) {
	config2 := _wireConfigValue
	httpHttpConfig := config2.http
	httpHttpServer, err := newHTTPServer(httpHttpConfig)
	if err != nil {
		return nil, nil, err
	}
	commonConfig := config2.common
	mongoConfig := config2.mongo
	database, cleanup, err := mongo.NewMongoDatabase(mongoConfig)
	if err != nil {
		return nil, nil, err
	}
	userRepository := mongo2.NewUserRepository(database)
	userService := service.NewUserService(userRepository)
	goPlaygroundValidator := validator.NewGoPlayValidator()
	userHandler := handler.NewUserHandler(userService, goPlaygroundValidator)
	authService := service.NewAuthService(commonConfig, userRepository)
	authHandler := handler.NewAuthHandler(authService, goPlaygroundValidator)
	matchingRepository := mongo2.NewMatchingRepository(database)
	matchingService := service.NewMatchingService(matchingRepository, userRepository)
	helper := jwt.NewHelper(userService)
	matchingHandler := handler.NewMatchingHandler(matchingService, goPlaygroundValidator, helper)
	subscriptionRepository := mongo2.NewSubscriptionRepository(database)
	subscriptionServicer := service.NewSubscriptionService(subscriptionRepository)
	subscriptionHandler := handler.NewSubscriptionHandler(subscriptionServicer)
	httpHttpRouter := newRouter(commonConfig, userHandler, authHandler, matchingHandler, subscriptionHandler)
	httpApp := newApp(config2, httpHttpServer, httpHttpRouter, database)
	return httpApp, func() {
		cleanup()
	}, nil
}

var (
	_wireConfigValue = cfg
)

// injector.go:

var cfg = loadConfig()

var configSet = wire.NewSet(wire.Value(cfg), wire.FieldsOf(
	new(config),
	"common",
	"http",
	"mongo"),
)

var handlerSet = wire.NewSet(handler.NewUserHandler, handler.NewAuthHandler, handler.NewMatchingHandler, handler.NewSubscriptionHandler)

var serviceSet = wire.NewSet(service.NewUserService, wire.Bind(new(internal.UserServicer), new(*service.UserService)), service.NewAuthService, wire.Bind(new(internal.AuthServicer), new(*service.AuthService)), service.NewMatchingService, wire.Bind(new(internal.MatchingServicer), new(*service.MatchingService)), service.NewSubscriptionService, wire.Bind(new(internal.SubscriptionServicer), new(*service.SubscriptionServicer)))

var repoSet = wire.NewSet(mongo2.NewUserRepository, wire.Bind(new(internal.UserRepositorier), new(*mongo2.UserRepository)), mongo2.NewMatchingRepository, wire.Bind(new(internal.MatchingRepositorier), new(*mongo2.MatchingRepository)), mongo2.NewSubscriptionRepository, wire.Bind(new(internal.SubscriptionRepositorier), new(*mongo2.SubscriptionRepository)))

var driverSet = wire.NewSet(mongo.NewMongoDatabase)

var pkgSet = wire.NewSet(validator.NewGoPlayValidator, wire.Bind(new(validator.Validator), new(*validator.GoPlaygroundValidator)), jwt.NewHelper)
