// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "com.ardafirdausr.cupid/internal/dto"
	entity "com.ardafirdausr.cupid/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockUserRepositorier is a mock of UserRepositorier interface.
type MockUserRepositorier struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositorierMockRecorder
}

// MockUserRepositorierMockRecorder is the mock recorder for MockUserRepositorier.
type MockUserRepositorierMockRecorder struct {
	mock *MockUserRepositorier
}

// NewMockUserRepositorier creates a new mock instance.
func NewMockUserRepositorier(ctrl *gomock.Controller) *MockUserRepositorier {
	mock := &MockUserRepositorier{ctrl: ctrl}
	mock.recorder = &MockUserRepositorierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepositorier) EXPECT() *MockUserRepositorierMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserRepositorier) CreateUser(ctx context.Context, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserRepositorierMockRecorder) CreateUser(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserRepositorier)(nil).CreateUser), ctx, user)
}

// GetUserByEmail mocks base method.
func (m *MockUserRepositorier) GetUserByEmail(ctx context.Context, email string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserRepositorierMockRecorder) GetUserByEmail(ctx, email interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserRepositorier)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserRepositorier) GetUserByID(ctx context.Context, id string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserRepositorierMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserRepositorier)(nil).GetUserByID), ctx, id)
}

// UpdateUserByID mocks base method.
func (m *MockUserRepositorier) UpdateUserByID(ctx context.Context, id string, user *entity.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserByID", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserByID indicates an expected call of UpdateUserByID.
func (mr *MockUserRepositorierMockRecorder) UpdateUserByID(ctx, id, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserByID", reflect.TypeOf((*MockUserRepositorier)(nil).UpdateUserByID), ctx, id, user)
}

// MockMatchingRepositorier is a mock of MatchingRepositorier interface.
type MockMatchingRepositorier struct {
	ctrl     *gomock.Controller
	recorder *MockMatchingRepositorierMockRecorder
}

// MockMatchingRepositorierMockRecorder is the mock recorder for MockMatchingRepositorier.
type MockMatchingRepositorierMockRecorder struct {
	mock *MockMatchingRepositorier
}

// NewMockMatchingRepositorier creates a new mock instance.
func NewMockMatchingRepositorier(ctrl *gomock.Controller) *MockMatchingRepositorier {
	mock := &MockMatchingRepositorier{ctrl: ctrl}
	mock.recorder = &MockMatchingRepositorierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchingRepositorier) EXPECT() *MockMatchingRepositorierMockRecorder {
	return m.recorder
}

// CreateMatching mocks base method.
func (m *MockMatchingRepositorier) CreateMatching(ctx context.Context, matching *entity.Matching) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMatching", ctx, matching)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMatching indicates an expected call of CreateMatching.
func (mr *MockMatchingRepositorierMockRecorder) CreateMatching(ctx, matching interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMatching", reflect.TypeOf((*MockMatchingRepositorier)(nil).CreateMatching), ctx, matching)
}

// GetMatchingByUser mocks base method.
func (m *MockMatchingRepositorier) GetMatchingByUser(ctx context.Context, user1ID, user2ID string) (*entity.Matching, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchingByUser", ctx, user1ID, user2ID)
	ret0, _ := ret[0].(*entity.Matching)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchingByUser indicates an expected call of GetMatchingByUser.
func (mr *MockMatchingRepositorierMockRecorder) GetMatchingByUser(ctx, user1ID, user2ID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchingByUser", reflect.TypeOf((*MockMatchingRepositorier)(nil).GetMatchingByUser), ctx, user1ID, user2ID)
}

// GetMatchingRecommendations mocks base method.
func (m *MockMatchingRepositorier) GetMatchingRecommendations(ctx context.Context, filter dto.MatchingRecommendationsFilter) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchingRecommendations", ctx, filter)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchingRecommendations indicates an expected call of GetMatchingRecommendations.
func (mr *MockMatchingRepositorierMockRecorder) GetMatchingRecommendations(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchingRecommendations", reflect.TypeOf((*MockMatchingRepositorier)(nil).GetMatchingRecommendations), ctx, filter)
}

// GetUserMatchingCount mocks base method.
func (m *MockMatchingRepositorier) GetUserMatchingCount(ctx context.Context, userID string, date time.Time) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserMatchingCount", ctx, userID, date)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserMatchingCount indicates an expected call of GetUserMatchingCount.
func (mr *MockMatchingRepositorierMockRecorder) GetUserMatchingCount(ctx, userID, date interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserMatchingCount", reflect.TypeOf((*MockMatchingRepositorier)(nil).GetUserMatchingCount), ctx, userID, date)
}

// UpdateMatchingByID mocks base method.
func (m *MockMatchingRepositorier) UpdateMatchingByID(ctx context.Context, matchingID string, matching *entity.Matching) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMatchingByID", ctx, matchingID, matching)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMatchingByID indicates an expected call of UpdateMatchingByID.
func (mr *MockMatchingRepositorierMockRecorder) UpdateMatchingByID(ctx, matchingID, matching interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMatchingByID", reflect.TypeOf((*MockMatchingRepositorier)(nil).UpdateMatchingByID), ctx, matchingID, matching)
}

// MockSubscriptionRepositorier is a mock of SubscriptionRepositorier interface.
type MockSubscriptionRepositorier struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositorierMockRecorder
}

// MockSubscriptionRepositorierMockRecorder is the mock recorder for MockSubscriptionRepositorier.
type MockSubscriptionRepositorierMockRecorder struct {
	mock *MockSubscriptionRepositorier
}

// NewMockSubscriptionRepositorier creates a new mock instance.
func NewMockSubscriptionRepositorier(ctrl *gomock.Controller) *MockSubscriptionRepositorier {
	mock := &MockSubscriptionRepositorier{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositorierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepositorier) EXPECT() *MockSubscriptionRepositorierMockRecorder {
	return m.recorder
}

// CreateUserSubscription mocks base method.
func (m *MockSubscriptionRepositorier) CreateUserSubscription(ctx context.Context, subscription *entity.UserSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserSubscription", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUserSubscription indicates an expected call of CreateUserSubscription.
func (mr *MockSubscriptionRepositorierMockRecorder) CreateUserSubscription(ctx, subscription interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserSubscription", reflect.TypeOf((*MockSubscriptionRepositorier)(nil).CreateUserSubscription), ctx, subscription)
}

// GetActiveUserSubscriptionByUserID mocks base method.
func (m *MockSubscriptionRepositorier) GetActiveUserSubscriptionByUserID(ctx context.Context, userID string) (*entity.UserSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUserSubscriptionByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.UserSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUserSubscriptionByUserID indicates an expected call of GetActiveUserSubscriptionByUserID.
func (mr *MockSubscriptionRepositorierMockRecorder) GetActiveUserSubscriptionByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUserSubscriptionByUserID", reflect.TypeOf((*MockSubscriptionRepositorier)(nil).GetActiveUserSubscriptionByUserID), ctx, userID)
}

// GetAllSubscriptions mocks base method.
func (m *MockSubscriptionRepositorier) GetAllSubscriptions(ctx context.Context) ([]entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubscriptions", ctx)
	ret0, _ := ret[0].([]entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubscriptions indicates an expected call of GetAllSubscriptions.
func (mr *MockSubscriptionRepositorierMockRecorder) GetAllSubscriptions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubscriptions", reflect.TypeOf((*MockSubscriptionRepositorier)(nil).GetAllSubscriptions), ctx)
}

// GetSubscriptionByID mocks base method.
func (m *MockSubscriptionRepositorier) GetSubscriptionByID(ctx context.Context, subscriptionID string) (*entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionByID", ctx, subscriptionID)
	ret0, _ := ret[0].(*entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionByID indicates an expected call of GetSubscriptionByID.
func (mr *MockSubscriptionRepositorierMockRecorder) GetSubscriptionByID(ctx, subscriptionID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionByID", reflect.TypeOf((*MockSubscriptionRepositorier)(nil).GetSubscriptionByID), ctx, subscriptionID)
}
