// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	dto "com.ardafirdausr.cupid/internal/dto"
	entity "com.ardafirdausr.cupid/internal/entity"
	gomock "github.com/golang/mock/gomock"
)

// MockUserServicer is a mock of UserServicer interface.
type MockUserServicer struct {
	ctrl     *gomock.Controller
	recorder *MockUserServicerMockRecorder
}

// MockUserServicerMockRecorder is the mock recorder for MockUserServicer.
type MockUserServicerMockRecorder struct {
	mock *MockUserServicer
}

// NewMockUserServicer creates a new mock instance.
func NewMockUserServicer(ctrl *gomock.Controller) *MockUserServicer {
	mock := &MockUserServicer{ctrl: ctrl}
	mock.recorder = &MockUserServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServicer) EXPECT() *MockUserServicerMockRecorder {
	return m.recorder
}

// GetUserByID mocks base method.
func (m *MockUserServicer) GetUserByID(ctx context.Context, id string) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserServicerMockRecorder) GetUserByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserServicer)(nil).GetUserByID), ctx, id)
}

// UpdateUser mocks base method.
func (m *MockUserServicer) UpdateUser(ctx context.Context, param dto.UpdateUserParam) (*entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, param)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockUserServicerMockRecorder) UpdateUser(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockUserServicer)(nil).UpdateUser), ctx, param)
}

// MockAuthServicer is a mock of AuthServicer interface.
type MockAuthServicer struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServicerMockRecorder
}

// MockAuthServicerMockRecorder is the mock recorder for MockAuthServicer.
type MockAuthServicerMockRecorder struct {
	mock *MockAuthServicer
}

// NewMockAuthServicer creates a new mock instance.
func NewMockAuthServicer(ctrl *gomock.Controller) *MockAuthServicer {
	mock := &MockAuthServicer{ctrl: ctrl}
	mock.recorder = &MockAuthServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthServicer) EXPECT() *MockAuthServicerMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthServicer) Login(ctx context.Context, param dto.LoginUserParam) (*entity.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, param)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockAuthServicerMockRecorder) Login(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthServicer)(nil).Login), ctx, param)
}

// Register mocks base method.
func (m *MockAuthServicer) Register(ctx context.Context, param dto.RegisterUserParam) (*entity.User, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, param)
	ret0, _ := ret[0].(*entity.User)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Register indicates an expected call of Register.
func (mr *MockAuthServicerMockRecorder) Register(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthServicer)(nil).Register), ctx, param)
}

// MockMatchingServicer is a mock of MatchingServicer interface.
type MockMatchingServicer struct {
	ctrl     *gomock.Controller
	recorder *MockMatchingServicerMockRecorder
}

// MockMatchingServicerMockRecorder is the mock recorder for MockMatchingServicer.
type MockMatchingServicerMockRecorder struct {
	mock *MockMatchingServicer
}

// NewMockMatchingServicer creates a new mock instance.
func NewMockMatchingServicer(ctrl *gomock.Controller) *MockMatchingServicer {
	mock := &MockMatchingServicer{ctrl: ctrl}
	mock.recorder = &MockMatchingServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMatchingServicer) EXPECT() *MockMatchingServicerMockRecorder {
	return m.recorder
}

// GetMatchingRecommendations mocks base method.
func (m *MockMatchingServicer) GetMatchingRecommendations(ctx context.Context, filter dto.MatchingRecommendationsFilter) ([]entity.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMatchingRecommendations", ctx, filter)
	ret0, _ := ret[0].([]entity.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMatchingRecommendations indicates an expected call of GetMatchingRecommendations.
func (mr *MockMatchingServicerMockRecorder) GetMatchingRecommendations(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMatchingRecommendations", reflect.TypeOf((*MockMatchingServicer)(nil).GetMatchingRecommendations), ctx, filter)
}

// MatchMaking mocks base method.
func (m *MockMatchingServicer) MatchMaking(ctx context.Context, param dto.CreateMatchingParam) (*entity.Matching, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MatchMaking", ctx, param)
	ret0, _ := ret[0].(*entity.Matching)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MatchMaking indicates an expected call of MatchMaking.
func (mr *MockMatchingServicerMockRecorder) MatchMaking(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MatchMaking", reflect.TypeOf((*MockMatchingServicer)(nil).MatchMaking), ctx, param)
}

// MockSubscriptionServicer is a mock of SubscriptionServicer interface.
type MockSubscriptionServicer struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionServicerMockRecorder
}

// MockSubscriptionServicerMockRecorder is the mock recorder for MockSubscriptionServicer.
type MockSubscriptionServicerMockRecorder struct {
	mock *MockSubscriptionServicer
}

// NewMockSubscriptionServicer creates a new mock instance.
func NewMockSubscriptionServicer(ctrl *gomock.Controller) *MockSubscriptionServicer {
	mock := &MockSubscriptionServicer{ctrl: ctrl}
	mock.recorder = &MockSubscriptionServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionServicer) EXPECT() *MockSubscriptionServicerMockRecorder {
	return m.recorder
}

// CreateUserSubscription mocks base method.
func (m *MockSubscriptionServicer) CreateUserSubscription(ctx context.Context, param dto.CreateUserSubscriptionParam) (*entity.UserSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserSubscription", ctx, param)
	ret0, _ := ret[0].(*entity.UserSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserSubscription indicates an expected call of CreateUserSubscription.
func (mr *MockSubscriptionServicerMockRecorder) CreateUserSubscription(ctx, param interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserSubscription", reflect.TypeOf((*MockSubscriptionServicer)(nil).CreateUserSubscription), ctx, param)
}

// GetActiveUserSubscription mocks base method.
func (m *MockSubscriptionServicer) GetActiveUserSubscription(ctx context.Context) (*entity.UserSubscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUserSubscription", ctx)
	ret0, _ := ret[0].(*entity.UserSubscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUserSubscription indicates an expected call of GetActiveUserSubscription.
func (mr *MockSubscriptionServicerMockRecorder) GetActiveUserSubscription(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUserSubscription", reflect.TypeOf((*MockSubscriptionServicer)(nil).GetActiveUserSubscription), ctx)
}

// GetAllSubscriptions mocks base method.
func (m *MockSubscriptionServicer) GetAllSubscriptions(ctx context.Context) ([]entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllSubscriptions", ctx)
	ret0, _ := ret[0].([]entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllSubscriptions indicates an expected call of GetAllSubscriptions.
func (mr *MockSubscriptionServicerMockRecorder) GetAllSubscriptions(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllSubscriptions", reflect.TypeOf((*MockSubscriptionServicer)(nil).GetAllSubscriptions), ctx)
}
